{% set version = '1.0-17' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sets
  version: {{ version|replace("-", "_") }}

source:
  fn: sets_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/sets_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/sets/sets_{{ version }}.tar.gz
  sha256: 17817a386d725a458d95368795e4c31ef5dbc00439df24daf9bda996bfe767c5

build:
  merge_build_host: True  # [win]
  number: 2
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('sets')"  # [not win]
    - "\"%R%\" -e \"library('sets')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=sets
  license: GPL-2
  summary: Data structures and basic operations for ordinary sets, generalizations such as fuzzy
    sets, multisets, and fuzzy multisets, customizable sets, and intervals.
  license_family: GPL2

extra:
  recipe-maintainers:
    - dpryan79
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
