travis:
  secure:
    BINSTAR_TOKEN: pYBXj35V2eD8Mtt1XxGcHTnrc7iLwOQNbqZ79/UZSWWGZTW9NL6v1HNiqTPrSi8YzTtU1x5SlvGJcyivHeSgnjTzsAlIXrSEPa5M/bf6HM4RXhm5bchJgGojQpZ++RUR+ZNCEROtLymQclhvlLNaQPYnZFcoxLu4th+K6p/308JggGwUS8jd6+bIFfhl3oGTud7rfjNBa9C2ZCGoYmoA67pnWsQt198FOgXIF9UkolgPOR0aRGMaluIrpoHrPDiSlLlanS4u8vyNO1IDOulREN7afDoVPeuqLRJMhTwNlbFcf9UnxT2qGIxDQgErF/RhD8YHKd5oVMM2a/GRDpFqlJnSsIE7thP3NRIqHV/3vilDdFjNvdVzgfDlAYdGbb4ddxmXTbtm5IkzE2pajcf3PV9MSmPzsQdtCtBuTDXlFXE/dK0bwpoKAOlz2AmtXplQICUTMixCQQfKf/CuABW5aNYfTZ+O0W+WULOQX4KP8ua/UEiIjFw3Uca9zfYnvFSYTrAtHpzuB+6LOvAJsxonxXqJDWRmOA8D89i2tkXkTOx/Cte6OwOXsr18pcbrIEzzTjfSF3zAa4LysxG9nVp3JoXHxjv4XBPSnNcOKQUAB9tSL9l+XKxpuaPJgCMIbSAmVQl1XulT9Cn6/+MhkUmlHS9LTxKqkmMoW/LC4POEgAs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
