travis:
  secure:
    BINSTAR_TOKEN: v9/jSY4j7AvPo9MfhSIQ6yxG5XEzHXCpDiHqKvrh5DlzynTFRGgGvQiv7fyZZFCfX0+umO01s8rcozxvdUIZiXzzjiB1vOTt6+nVZPCdZrcWv4zZV0PbpF4DYePmA8g9z+upHe/VugI/UkyprplMqam9+wKo1zZ2fzu/dOhUK/RCSfa52fiFS8WMVxyzVj+BBywEIb/nfM/x3LxP7VQ3B84sNuWWq0h2zrVb+T8Q5bRpXzWf3EiiSlh8sey9PqMZyDDNLL0oq4mjIvFr3UtJ84YVBYAqdSUfoCikhYiqK2BiUU3WI7xgyy6/JotSO55cLpIOz6mTtXRlPEnxJ+hml/Y7un5OCC/912NeIhPQ2B02dn4PFxwIzkxNI+PqO22IrvVURwR523gOjD8koVK6P7jnoD7SbF5NDBqEZHksxUNCpDxZK8ePEeyTMgSrxPYQLkmzELS/gRuCu09wMKOWGBH7LQQsVw3cNRt4VsrX8B/9HcF9GuG+HEG68UZfpPPLKgBUm+ijB89qn3VxaCuskeWaZ1DRctxC12kpu0cFtp+Mo2aymCwNucTLoluaBXaXyYgOriUF5FDdZNgay3a67w1Zi9n/klY4DzqmU3/hbj93ZhwM4751xFIfHOUK2NJjxnkwFtBTtiObfvGhmqTzJqVA3JRrnaRTU72G2DNm15M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
