travis:
  secure:
    BINSTAR_TOKEN: DCkI+KBDA7vjL+4t873tdob5+3IMTuBvHv5NBZ7DM3m1FedMTYF05tlsV9VishLBKtVcwJeiuNvTDUhQctstwHvr+GENGrQYN2L2hGKOZYH2jTOsp0Z3BNfGkA09pZOHMint+M+9R2enYhFczk8KEaDV7Al9niK20MiHz/JK2yctylDyHAiTTXCSiLW7nUJOAclwi8Xav1S2Cnz2ijmF2fmezY0Xb2Mc7tH6b9tG8iuXA7YEf5bBkz60PSCaDKYThrMKNm4sTllnHsBlMneUmJqRSROO2etdwW5rq7PFtfrtXNd1oC/rS1Gy3Y+alX65iZo1BD9x3pgDBWhec3xn4kBP6/bIv32KiWXt//vNLG9hvS5gDBqccHpTiFxuA4qkQ5NGi3LMsSd6Csuty2OlLrT1MDa22qHoQzvGZknV1zj3ZlzRacbZFIqYkbpUF+u2lY05P8JL7h9Ntu5cfOxmpoSBRE66Uswyq1hoK68J/RE+va4E6BNghPzrf1ozJQpUG+Awq6VD093MY+3rY6KIZydIG4dKkN1Zo+yHpZlaeLzk7rF9Q2jXxfVvERsFxKLyMu6XlUTqjQoymGXocTNP66nY994+oXj0mGaWYp5UJm14GJum0xJYnP+n8e0F1XXCbjZRGOZkQo+MN3BFs+UMFXEfjxs9P5ByS38PyJaAvYw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
