travis:
  secure:
    BINSTAR_TOKEN: LXhDzKS3v8ul67snh7593M06avZeFeOPHAx29Sv2OqMnvFZDXUJ1vKJpl3/2Rsp6+tF+9cg7ZOF+hE1N/1VKPYUKWFobl1s3ED8LO1IwS7Um/Eloe1dm7sM2PKEXF5nBT8mUPslyo4u/UIAY87er8fpLrmLUUGZXfWCBi8gx+/bPxKrGbIngUAJOC/nJKgPZyIe2eCMf/Rz0dIr9UmR1FZhSA22VTLRybsjZD8EuT17EE9enZw0Z6IgzSn96k5KoCqaWB0V3coGZKxNc8ti5RudsBqaY8Chvk4keABx9RDZ29qfx3XpgaIT//UTdo1y2DPjntNFPUZ1+NIuJ2YjxuzH+PWTnDj4FDoTbV25IIS90ZdwzsbLh/yWCcsknXULTZ5zqdBspwRyacwd5G7wIV3QYn1PZbLMKMruxDYIGELM/FD9f+d53057prbk2fKOpv+gDm0CkF0P46+8tqCz/EYO1nW9sVQVksh1Vhb2nQ+O9RvRSZeUeJl3tzgQZTU7hqdJ52XviJQcr8nb+orBvwIAeW4hTHfGtn0xkfJHihKtJfoGYXwZQZparADzNWX0/oKCVkbjp9bUxmb6kD8l3K7JwNTpW/WVwGYm1HL/7D7o8VH9ZOPHb0uKpk8KHX/q+ZihpeZKPw4XoOBopvqHchuxcZuQXJOoAuohGqbBq8Uk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
